//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory.DBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfectioneryFactoryEntities : DbContext
    {
        public ConfectioneryFactoryEntities()
            : base("name=ConfectioneryFactoryEntities")
        {
        }

        private static ConfectioneryFactoryEntities _context;

        public static ConfectioneryFactoryEntities GetContext()
        {
            if (_context == null)
            {
                _context = new ConfectioneryFactoryEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logistics> Logistics { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
