//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID { get; set; }
        public Nullable<int> amountCereal { get; set; }
        public Nullable<int> amountOil { get; set; }
        public Nullable<int> amountSugar { get; set; }
        public Nullable<int> amountPowder { get; set; }
        public Nullable<int> amountWater { get; set; }
    }
}
